# Auto-generated by: docwrite(doc,"Shows the extended documentation of a pre-existing function.","function name","executes the .jl documentation macro","http://docs.julialang.org/en/latest/manual/","null","docwrite docaddex help methods","doc(abs)")
println("")
 println("Shows the extended documentation of a pre-existing function.")
 println("")
print_with_color(:white,"Input : ")
 println("function name")
print_with_color(:white,"Output: ")
 println("executes the .jl documentation macro")
 println("")
print("Julia specific help is located here online: ")
print_with_color(:magenta,"http://docs.julialang.org/en/latest/manual/
")
print("A good source of information about this is: ")
print_with_color(:magenta,"null
")
println("")
 print_with_color(:white,"See Also: ")
print_with_color(:black,"docwrite docaddex help methods
")
println("")
 print_with_color(:white,"Source Code: ")
println("to see where the source code is located call the function methods(doc) ")
println("")
 print_with_color(:white,"Examples:

")
print_with_color(:green,"julia> ") ; println("doc(abs)")
# doc(abs)

