# Auto-generated by: docwrite(docaddex,"Adds examples to pre-existing documentation a function.","function name","appends examples to the .jl documenation macro","http://docs.julialang.org/en/latest/manual/","null","docwrite docaddex help methods","docaddex(abs,"num=12+5im","abs(num)")")
println("")
 println("Adds examples to pre-existing documentation a function.")
 println("")
print_with_color(:white,"Input : ")
 println("function name")
print_with_color(:white,"Output: ")
 println("appends examples to the .jl documenation macro")
 println("")
print("Julia specific help is located here online: ")
print_with_color(:magenta,"http://docs.julialang.org/en/latest/manual/
")
print("A good source of information about this is: ")
print_with_color(:magenta,"null
")
println("")
 print_with_color(:white,"See Also: ")
print_with_color(:black,"docwrite docaddex help methods
")
println("")
 print_with_color(:white,"Source Code: ")
println("to see where the source code is located call the function methods(docaddex) ")
println("")
 print_with_color(:white,"Examples:

")
print_with_color(:green,"julia> ") ; println("docaddex(abs,\"num=12+5im\",\"abs(num)\")")
# docaddex(abs,"num=12+5im","abs(num)")

