# Auto-generated by: docwrite(docwrite,"Generates documentation for pre-existing functions","function name","writes a .jl executable file that contains all the new documentation","http://docs.julialang.org/en/latest/manual/","null","doc docaddex help methods","docwrite(abs,"Takes the absolute value","x can be integer, float, complex, matrix or array and many more","a positive number or array of the same type, i.e. the abs(float) will return a float","http://docs.julialang.org/en/latest/stdlib/base/?highlight=abs#Base.abs","http://mathworld.wolfram.com/AbsoluteValue.html","norm Int Float64 Complex","x=2","abs(x)","println(abs(x))","y=-3","abs(y)","println(abs(y))","z=-4.9384","abs(z)","println(abs(z))","t=3+4im","println(abs(t))","println(abs([x,y,z,t]))")")
println("")
 println("Generates documentation for pre-existing functions")
 println("")
print_with_color(:white,"Input : ")
 println("function name")
print_with_color(:white,"Output: ")
 println("writes a .jl executable file that contains all the new documentation")
 println("")
print("Julia specific help is located here online: ")
print_with_color(:magenta,"http://docs.julialang.org/en/latest/manual/
")
print("A good source of information about this is: ")
print_with_color(:magenta,"null
")
println("")
 print_with_color(:white,"See Also: ")
print_with_color(:black,"doc docaddex help methods
")
println("")
 print_with_color(:white,"Source Code: ")
println("to see where the source code is located call the function methods(docwrite) ")
println("")
 print_with_color(:white,"Examples:

")
print_with_color(:green,"julia> ") ; println("docwrite(abs,\"Takes the absolute value\",\"x can be integer, float, complex, matrix or array and many more\",\"a positive number or array of the same type, i.e. the abs(float) will return a float\",\"http://docs.julialang.org/en/latest/stdlib/base/?highlight=abs\#Base.abs\",\"http://mathworld.wolfram.com/AbsoluteValue.html\",\"norm Int Float64 Complex\",\"x=2\",\"abs(x)\",\"println(abs(x))\",\"y=-3\",\"abs(y)\",\"println(abs(y))\",\"z=-4.9384\",\"abs(z)\",\"println(abs(z))\",\"t=3+4im\",\"println(abs(t))\",\"println(abs([x,y,z,t]))\")")
# docwrite(abs,"Takes the absolute value","x can be integer, float, complex, matrix or array and many more","a positive number or array of the same type, i.e. the abs(float) will return a float","http://docs.julialang.org/en/latest/stdlib/base/?highlight=abs#Base.abs","http://mathworld.wolfram.com/AbsoluteValue.html","norm Int Float64 Complex","x=2","abs(x)","println(abs(x))","y=-3","abs(y)","println(abs(y))","z=-4.9384","abs(z)","println(abs(z))","t=3+4im","println(abs(t))","println(abs([x,y,z,t]))")
# docwrite(abs,"Takes the absolute value","x can be integer, float, complex, matrix or array and many more","a positive number or array of the same type, i.e. the abs(float) will return a float","http://docs.julialang.org/en/latest/stdlib/base/?highlight=abs#Base.abs","http://mathworld.wolfram.com/AbsoluteValue.html","norm Int Float64 Complex","x=2","abs(x)","println(abs(x))","y=-3","abs(y)","println(abs(y))","z=-4.9384","abs(z)","println(abs(z))","t=3+4im","println(abs(t))","println(abs([x,y,z,t]))")

