# Auto-generated by: docwrite(foo,"does bar","no input","outputs bar","www.foobar.com","www.barfoo.com","foo bar","foo()")
println("")
 println("does bar")
 println("")
print_with_color(:white,"Input : ")
 println("no input")
print_with_color(:white,"Output: ")
 println("outputs bar")
 println("")
print("Julia specific help is located here online: ")
print_with_color(:magenta,"www.foobar.com
")
print("A good source of information about this is: ")
print_with_color(:magenta,"www.barfoo.com
")
println("")
 print_with_color(:white,"See Also: ")
print_with_color(:black,"foo bar
")
println("")
 print_with_color(:white,"Source Code: ")
println("to see where the source code is located call the function methods(foo) ")
println("")
 print_with_color(:white,"Examples:

")
print_with_color(:green,"julia> ") ; println("foo()")
foo()

# Appended examples generated by: docaddex(foo,"println(foo())")

print_with_color(:green,"julia> ") ; println("println(foo())")
println(foo())
