# Auto-generated by: docwrite(plot,"Makes a plot using the matplotlib. Must be using PyPlot","vector of x, vector of y, other arguments accepted by pyplot_api","the resulting plot in a canvas","https://github.com/stevengj/PyPlot.jl#the-pyplot-module-for-julia","http://matplotlib.org/api/pyplot_api.html","PyPlot matplotlib Vector linspace","using PyPlot ","x = linspace(0,2*pi,1000); y = sin(3*x + 4*cos(2*x));","plot(x, y, color="red", linewidth=2.0, linestyle="--")","title("A sinusoidally modulated sinusoid")")
println("")
 println("Makes a plot using the matplotlib. Must be using PyPlot")
 println("")
print_with_color(:white,"Input : ")
 println("vector of x, vector of y, other arguments accepted by pyplot_api")
print_with_color(:white,"Output: ")
 println("the resulting plot in a canvas")
 println("")
print("Julia specific help is located here online: ")
print_with_color(:magenta,"https://github.com/stevengj/PyPlot.jl#the-pyplot-module-for-julia
")
print("A good source of information about this is: ")
print_with_color(:magenta,"http://matplotlib.org/api/pyplot_api.html
")
println("")
 print_with_color(:white,"See Also: ")
print_with_color(:black,"PyPlot matplotlib Vector linspace
")
println("")
 print_with_color(:white,"Source Code: ")
println("to see where the source code is located call the function methods(plot) ")
println("http://www.google.com")
println("")
 print_with_color(:white,"Examples:

")
print_with_color(:green,"julia> ") ; println("using PyPlot ")
using PyPlot 
print_with_color(:green,"julia> ") ; println("x = linspace(0,2*pi,1000); y = sin(3*x + 4*cos(2*x));")
x = linspace(0,2*pi,1000); y = sin(3*x + 4*cos(2*x));
print_with_color(:green,"julia> ") ; println("plot(x, y, color=\"red\", linewidth=2.0, linestyle=\"--\")")
plot(x, y, color="red", linewidth=2.0, linestyle="--")
print_with_color(:green,"julia> ") ; println("title(\"A sinusoidally modulated sinusoid\")")
title("A sinusoidally modulated sinusoid")